#!/bin/sh
# Strip Co-Authored-By and other attribution lines
sed -i '' '/^[Cc]o-[Aa]uthored-[Bb]y:/d' "$1"
# Remove trailing blank lines
perl -i -0pe 's/\n+$/\n/' "$1"

# Delegate to local project hook if exists
if [ -x ".git/hooks/commit-msg" ]; then
  exec ".git/hooks/commit-msg" "$@"
fi
