#!/usr/bin/env sh

sudo yabai --load-sa

# ----------------------------------------------------------------------------------------------------------------------

yabai -m signal --add event=dock_did_restart	action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused		action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created		action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed	action="sketchybar --trigger windows_on_spaces"

# ----------------------------------------------------------------------------------------------------------------------

yabai -m config external_bar				all:0:38

yabai -m config mouse_follows_focus			on 
yabai -m config focus_follows_mouse			off 

yabai -m config window_zoom_persist			off
yabai -m config window_placement			second_child
yabai -m config window_topmost				off

yabai -m config window_opacity on
yabai -m config window_opacity_duration		0.125
yabai -m config active_window_opacity		1.0
yabai -m config normal_window_opacity		0.85
yabai -m config window_animation_duration	0

yabai -m config insert_feedback_color		0xff9dd274
yabai -m config split_ratio					0.5
yabai -m config auto_balance				off
yabai -m config auto_padding				on
yabai -m config layout						bsp

yabai -m config mouse_modifier				shift
yabai -m config mouse_action1				move
yabai -m config mouse_action2				resize
yabai -m config mouse_drop_action			swap

yabai -m config top_padding					8
yabai -m config bottom_padding				10
yabai -m config left_padding				10
yabai -m config right_padding				10
yabai -m config window_gap					10

# ----------------------------------------------------------------------------------------------------------------------

function space_destroy_amount {
	for idx in $(yabai -m query --spaces | jq ".[].index | select(. > $1)" | sort -nr); do
		yabai -m space --destroy "$idx"
	done
}

function space_create {
	local idx="$1"
	local name="$2"
	local space=$(yabai -m query --spaces --space "$idx")

	if [ -z "$space" ]; then
		yabai -m space --create
	fi

	yabai -m space "$idx" --label "$name"
}

space_destroy_amount 10

space_create 1 term
space_create 2 browser
space_create 3 reflection
space_create 4 design
space_create 5 explorer
space_create 6 games
space_create 7 other
space_create 8 media
space_create 9 calls
space_create 10 social

# ----------------------------------------------------------------------------------------------------------------------

yabai -m rule --add space=term			app="^(WezTerm)$"
yabai -m rule --add space=browser		app="^(Google Chrome)$"
yabai -m rule --add space=reflection	app="^(Mail|NetNewsWire|Things)$"
yabai -m rule --add space=design		app="^(Figma|Miro)$"
yabai -m rule --add space=explorer		app="^(Finder)$"
yabai -m rule --add space=games			app="^(Steam Helper|Dota 2)$"
yabai -m rule --add space=media			app="^(Яндекс Музыка|Photos)$"
yabai -m rule --add space=calls			app="^(zoom.us|Толк)$"
yabai -m rule --add space=social		app="^(Telegram|Slack|Discord|WhatsApp)$"

# ----------------------------------------------------------------------------------------------------------------------

yabai -m rule --add manage=off app!="^(\
Figma|\
Finder|\
Google Chrome|\
Mail|\
Miro|\
NetNewsWire|\
Slack|\
Telegram|\
Things|\
WezTerm|\
zoom.us|\
Толк\
)$"

yabai -m rule --add manage=off app="^Finder$" title="(Copy|Connect|Move|Info|Pref|Finder Settings)"
