#!/usr/bin/env zsh

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
sudo yabai --load-sa

# -- Events ------------------------------------------------------------------------------------------------------------

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# -- Config ------------------------------------------------------------------------------------------------------------

yabai -m config \
	external_bar all:0:38 \
	debug_output off \
	mouse_follows_focus on \
	focus_follows_mouse off \
	window_zoom_persist off \
	window_placement second_childwindow_topmost offwindow_shadow off \
	window_opacity on \
	window_opacity_duration 0.15 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.95 \
	insert_feedback_color 0x00ffffff \
	split_ratio 0.55 \
	auto_balance off \
	auto_padding on \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	top_padding 8 \
	bottom_padding 8 \
	left_padding 8 \
	right_padding 8 \
	window_gap 8

# -- Space preparing ---------------------------------------------------------------------------------------------------

function space_destroy_amount {
	for idx in $(yabai -m query --spaces | jq ".[].index | select(. > $1)" | sort -nr); do
		yabai -m space --destroy "$idx"
	done
}

function space_create {
	local display=$(display_index_get $1)
	local idx=$2
	local name=$3
	local space=$(yabai -m query --spaces | jq "first(.[] | select(.index == $idx) | .index)")

	if [ -z "$space" ]; then
		yabai -m space --create
	fi

	yabai -m space "$idx" --label "$name" --display "$display"
}

space_destroy_amount 10

space_create 1 1 term
space_create 1 2 browser
space_create 1 3 reflection
space_create 1 4 design
space_create 1 5 explorer
space_create 1 6 games
space_create 2 7 other
space_create 2 8 media
space_create 2 9 calls
space_create 2 10 social

# -- Assigning windows in spaces ---------------------------------------------------------------------------------------

yabai -m rule --add space=term app="^(WezTerm)$"
yabai -m rule --add space=browser app="^(Google Chrome)$"
yabai -m rule --add space=reflection app="^(Mail|NetNewsWire|Things)$"
yabai -m rule --add space=design app="^(Figma|Miro)$"
yabai -m rule --add space=explorer app="^(Finder)$"
yabai -m rule --add space=games app="^(Steam Helper|Dota 2)$"
yabai -m rule --add space=media app="^(Яндекс Музыка|Photos)$"
yabai -m rule --add space=calls app="^(zoom.us|Толк)$"
yabai -m rule --add space=social app="^(Telegram|Slack|Discord|WhatsApp)$"

# -- Layout managing ---------------------------------------------------------------------------------------------------

yabai -m rule --add manage=off app!="^(\
Figma|\
Finder|\
Calendar|\
Google Chrome|\
Mail|\
Miro|\
NetNewsWire|\
Slack|\
Telegram|\
Things|\
WezTerm|\
WhatsApp|\
zoom.us|\
Толк|\
Яндекс Музыка\
)$"

yabai -m rule --add manage=off app="^Finder$" title="(Copy|Connect|Move|Info|Pref|Finder Settings)"
yabai -m rule --add manage=off app="^Slack$" title="^Huddle"
yabai -m rule --add manage=off app="^Things$" title="(Quick Entry)"
