# Конфигурация markdownlint.
# Документация правил: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Разрешить длинные строки — в документации часто встречаются длинные ссылки и таблицы
MD013: false

# Разрешить inline HTML — используется в README для бейджей и изображений
MD033: false

# Разрешить дублирование заголовков в разных секциях (например, "Installation" в нескольких docs)
MD024:
  siblings_only: true

# Разрешить несколько заголовков первого уровня (некоторые .md файлы — не документы с одним h1)
MD025: false

# Разрешить отсутствие пустой строки перед списком внутри blockquote
MD032: false
