#!/usr/bin/env fish
# vi: ft=fish

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
sudo yabai --load-sa

# -- Events ------------------------------------------------------------------------------------------------------------

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_created action="fish -c 'yabai.rearrange'"

# -- Config ------------------------------------------------------------------------------------------------------------

yabai -m config \
    external_bar all:0:42 \
    debug_output off \
    mouse_follows_focus off \
    focus_follows_mouse off \
    window_zoom_persist off \
    window_placement second_child \
    window_topmost off \
    window_shadow off \
    window_opacity on \
    window_opacity_duration 0.15 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.95 \
    insert_feedback_color 0x00ffffff \
    split_ratio 0.53 \
    auto_balance off \
    auto_padding on \
    layout bsp \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    top_padding 6 \
    bottom_padding 4 \
    left_padding 4 \
    right_padding 4 \
    window_gap 6

# -- Space preparing ---------------------------------------------------------------------------------------------------

function space_destroy_amount
    for idx in (yabai -m query --spaces | jq ".[].index | select(. > $argv[1])" | sort -nr)
        yabai -m space --destroy "$idx"
    end
end

function space_create
    set -l display (yabai_display_index_get $argv[1])
    set -l idx $argv[2]
    set -l name $argv[3]
    set -l space (yabai -m query --spaces | jq "first(.[] | select(.index == $idx) | .index)")

    if test -z "$space"
        yabai -m space --create
    end

    yabai -m space "$idx" --label "$name" --display "$display"
end

space_destroy_amount 12

space_create 1 1 Code
space_create 1 2 Serf
space_create 1 3 Org
space_create 1 4 Graph
space_create 1 5 Explr
space_create 1 6 Fun
space_create 2 7 Sys
space_create 2 8 Ai
space_create 2 9 Any
space_create 2 10 Social
space_create 2 11 Calls
space_create 2 12 Media

# -- Assigning windows in spaces ---------------------------------------------------------------------------------------

yabai -m rule --add app="^.*\$" space="Any"
yabai -m rule --add space="Code" app="^(WezTerm|Ghostty|Code|Cursor|Zed)\$"
yabai -m rule --add space="Serf" app="^(Arc|Dia|Google Chrome)\$"
yabai -m rule --add space="Org" app="^(Things|Calendar|Mail)\$"
yabai -m rule --add space="Graph" app="^(Figma|Miro)\$"
yabai -m rule --add space="Explr" app="^(Finder|Cyberduck)\$"
yabai -m rule --add space="Fun" app="^(Steam Helper|Dota 2)\$"
yabai -m rule --add space="Sys" app="^(System Settings|MacPass)\$"
yabai -m rule --add space="Media" app="^(Yandex Music|Photos)\$"
yabai -m rule --add space="Calls" app="^(Толк)\$"
yabai -m rule --add space="Social" app="^(Time|Telegram|WhatsApp)\$"
yabai -m rule --add space="Ai" app="^(ChatGPT|Claude|Perplexity)\$"

# -- Layout managing ---------------------------------------------------------------------------------------------------

yabai -m rule --add manage=off app!="^(\
Arc|\
Calendar|\
Code|\
Cursor|\
Cyberduck|\
Dia|\
Figma|\
Finder|\
Ghostty|\
Google Chrome|\
MacPass|\
Mail|\
Miro|\
Perplexity|\
Telegram|\
Things|\
Time|\
WezTerm|\
WhatsApp|\
Yandex|\
Yandex Music|\
Толк\
)\$"

yabai -m rule --add app="^Calendar\$" title="General" manage=off
yabai -m rule --add app="^Mail\$" title="General" manage=off
yabai -m rule --add app="^Finder\$" title="(Copy|Connect|Move|Info|Pref|Finder Settings)" manage=off
yabai -m rule --add app="^Things\$" title="(Quick Entry)" manage=off

yabai -m rule --apply
