#!/usr/bin/env fish
# vi: ft=fish

# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
sudo yabai --load-sa

# -- Events ------------------------------------------------------------------------------------------------------------

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_created action="fish -c 'yabai.rearrange'"

# -- Config ------------------------------------------------------------------------------------------------------------

yabai -m config \
    external_bar all:0:42 \
    debug_output off \
    mouse_follows_focus off \
    focus_follows_mouse off \
    window_zoom_persist off \
    window_placement second_child \
    window_shadow off \
    window_opacity on \
    window_opacity_duration 0.15 \
    active_window_opacity 1.0 \
    normal_window_opacity 0.95 \
    insert_feedback_color 0x00ffffff \
    split_ratio 0.53 \
    auto_balance off \
    layout bsp \
    mouse_modifier fn \
    mouse_action1 move \
    mouse_action2 resize \
    mouse_drop_action swap \
    top_padding 6 \
    bottom_padding 4 \
    left_padding 4 \
    right_padding 4 \
    window_gap 6

# -- Space preparing ---------------------------------------------------------------------------------------------------

yabai.space_destroy_amount 12

yabai.space_create 2 9 Any -- ".*"
yabai.space_create 1 1 Code -- WezTerm Ghostty Code Cursor Zed
yabai.space_create 1 2 Serf -- Arc Dia "Google Chrome"
yabai.space_create 1 3 Org -- Things Calendar Mail
yabai.space_create 1 4 Graph -- Figma Miro
yabai.space_create 1 5 Explr -- Finder Cyberduck
yabai.space_create 1 6 Fun -- "Steam Helper" "Dota 2"
yabai.space_create 2 7 Sys -- "System Settings" MacPass
yabai.space_create 2 8 Ai -- ChatGPT Claude Perplexity
yabai.space_create 2 10 Social -- Time Telegram WhatsApp
yabai.space_create 2 11 Calls -- Толк
yabai.space_create 2 12 Media -- "Yandex Music" Photos

# -- Layout managing ---------------------------------------------------------------------------------------------------

yabai -m rule --add manage=off app=".*"

yabai.layout_add "Google Chrome"
yabai.layout_add "Yandex Music"
yabai.layout_add Arc
yabai.layout_add Calendar -- General
yabai.layout_add Code
yabai.layout_add Cursor
yabai.layout_add Cyberduck
yabai.layout_add Dia -- Settings
yabai.layout_add Figma
yabai.layout_add Finder -- Copy Connect Move Info Pref "Finder Settings"
yabai.layout_add Ghostty
yabai.layout_add Mail -- General
yabai.layout_add Miro
yabai.layout_add Perplexity
yabai.layout_add Telegram
yabai.layout_add Things -- "Quick Entry"
yabai.layout_add Time
yabai.layout_add WezTerm
yabai.layout_add WhatsApp
yabai.layout_add Yandex
yabai.layout_add Толк

yabai -m rule --apply

yabai.rearrange
