[manager]
ratio = [1, 2, 5]

[[manager.prepend_keymap]]
on = ["F"]
run = "plugin smart-filter"
desc = "Smart filter"

[opener]
edit = [
	{ run = 'nvr --remote-tab-wait +"setl bufhidden=wipe" "$@"', block = true },
]
extract = [
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[plugin]
prepend_previewers = [
	{ name = "*.csv", run = "duckdb" },
	{ name = "*.json", run = "duckdb" },
	{ name = "*.txt", run = "duckdb" },
	{ mime = "application/*zip", run = "ouch" },
	{ mime = "application/x-tar", run = "ouch" },
	{ mime = "application/x-bzip2", run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar", run = "ouch" },
	{ mime = "application/x-xz", run = "ouch" },
	{ mime = "application/xz", run = "ouch" },
]
prepend_preloaders = [
	{ name = "*.csv", run = "duckdb", multi = false },
	{ name = "*.json", run = "duckdb", multi = false },
	{ name = "*.txt", run = "duckdb", multi = false },
]
