local c_blend = require("util").color_blend

return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = 1000,

		opts = {
			integrations = {
				navic = false,
				treesitter_context = true,
				dap = { enabled = true, enable_ui = true },
			},
			highlight_overrides = {
				all = function(c)
					return {
						AerialLine = { fg = "none", bg = c.crust },
						AlphaFooter = { fg = c.surface1, style = {} },
						AlphaHeader1 = { fg = c.surface2 },
						AlphaHeader2 = { fg = c_blend(c.base, c.blue, 5) },
						AlphaHeader3 = { fg = c_blend(c.base, c.sky, 5) },
						AlphaHeader4 = { fg = c_blend(c.base, c.green, 5) },
						AlphaHeader5 = { fg = c_blend(c.base, c.yellow, 5) },
						AlphaHeader6 = { fg = c_blend(c.base, c.peach, 5) },
						AlphaHeader7 = { fg = c_blend(c.base, c.red, 5) },
						AlphaHeader8 = { fg = c.surface2 },
						AlphaShortcut = { bg = c_blend(c.base, c.crust, 50), fg = c_blend(c.base, c.surface1, 50) },
						AlphaShortcutBorder = { fg = c_blend(c.base, c.surface1, 50) },
						ChatGPTQuestion = { fg = c.mauve },
						ChatGPTTotalTokens = { bg = "none", fg = c.overlay2 },
						ChatGPTTotalTokensBorder = { fg = c.text },
						CmpDocFloat = { bg = c.mantle, blend = 15 },
						DiffviewDiffAdd = { bg = c_blend(c.green, c.base, 93) },
						DiffviewDiffDelete = { bg = c_blend(c.red, c.base, 93) },
						DiffviewNormal = { bg = c.mantle },
						DiffviewWinSeparator = { link = "NeoTreeWinSeparator" },
						EdgyNormal = { link = "NormalFloat" },
						EdgyTitle = { bg = c.mantle },
						FlashPrompt = { bg = c.mantle },
						FloatBorder = { fg = c_blend(c.base, c.lavender, 50) },
						FloatTitle = { fg = c.lavender, style = { "bold" } },
						Folded = { bg = c.base, fg = c.surface2 },
						GitConflictCurrent = { bg = c_blend(c.blue, c.base, 90) },
						GitConflictCurrentLabel = { bg = c_blend(c.blue, c.base, 85) },
						GitConflictIncoming = { bg = c_blend(c.green, c.base, 90) },
						GitConflictIncomingLabel = { bg = c_blend(c.green, c.base, 85) },
						GitSignsAdd = { fg = c_blend(c.green, c.base, 50) },
						GitSignsAddInline = { bg = c_blend(c.green, c.base, 83) },
						GitSignsAddPreview = { bg = c_blend(c.green, c.base, 93) },
						GitSignsChange = { fg = c_blend(c.yellow, c.base, 50) },
						GitSignsDelete = { fg = c_blend(c.red, c.base, 50) },
						GitSignsDeleteInline = { bg = c_blend(c.red, c.base, 83) },
						GitSignsDeletePreview = { bg = c_blend(c.red, c.base, 93) },
						IblIndent = { fg = c_blend(c.base, c.surface2, 40) },
						IblScope = { fg = c_blend(c.base, c.surface2, 75) },
						LazyReasonKeys = { fg = c.overlay0 },
						NeoTreeCursorLine = { bg = c.crust },
						NeoTreeDotfile = { fg = c.overlay0 },
						NeoTreeFadeText1 = { fg = c.surface1 },
						NeoTreeFadeText2 = { fg = c.surface2 },
						NeoTreeFileStats = { fg = c.surface1 },
						NeoTreeFileStatsHeader = { fg = c.surface2 },
						NeoTreeFloatBorder = { link = "FloatBorder" },
						NeoTreeFloatNormal = { link = "NormalFloat" },
						NeoTreeFloatTitle = { link = "FloatTitle" },
						NeoTreeMessage = { fg = c.surface1 },
						NeoTreeModified = { fg = c.peach },
						NeoTreeRootName = { fg = c.green },
						NeoTreeTabActive = { fg = c.text, bg = c_blend(c.base, c.text, 10) },
						NeoTreeTabSeparatorActive = { bg = c.base, fg = c.base },
						NeoTreeWinSeparator = { bg = c.base, fg = c.base },
						NoiceCmdline = { bg = c.mantle },
						NoiceCmdlinePopupBorder = { link = "FloatBorder" },
						NoiceScrollbar = { link = "NormalFloat" },
						NoiceScrollbarThumb = { bg = c_blend(c.base, c.surface0, 50) },
						NoicePopupmenuSelected = { link = "Visual" },
						NoiceFormatEvent = { fg = c.overlay1 },
						NoiceFormatKind = { fg = c.overlay0 },
						NoiceLspProgressTitle = { fg = c.overlay0 },
						NoicePopup = { link = "CmpDocFloat" },
						NonText = { fg = c.base },
						NormalFloat = { bg = c.base },
						TelescopeResultsDiffAdd = { link = "NeoTreeGitAdded" },
						TelescopeResultsDiffChange = { link = "NeoTreeGitModified" },
						TelescopeResultsDiffDelete = { link = "NeoTreeGitDeleted" },
						TelescopeResultsDiffUntracked = { link = "NeoTreeGitUntracked" },
						TelescopeSelection = { link = "Visual" },
						TelescopeTitle = { link = "FloatTitle" },
						TreesitterContext = { bg = c.base, blend = 10 },
						TreesitterContextBottom = { fg = c.surface2, blend = 0, style = { "underline" } },
						TreesitterContextLineNumber = { bg = c.base or c.base },
						TroubleCount = { bg = "none" },
						TroubleNormal = { link = "NormalFloat" },
						Visual = { style = {} },
						WhichKeyFloat = { bg = c.mantle },
						Whitespace = { fg = c.base },
						WinSeparator = { fg = c_blend(c.base, c.crust, 40) },
						ZenBg = { bg = c.mantle },
					}
				end,

				frappe = function(c)
					return {
						AerialGuide = { fg = c.surface0 },
						GitSignsCurrentLineBlame = { fg = c.surface2 },
						IlluminatedWordRead = { bg = c_blend(c.base, c.surface2, 25) },
						IlluminatedWordText = { bg = c_blend(c.base, c.sapphire, 25) },
						IlluminatedWordWrite = { bg = c_blend(c.base, c.sapphire, 25) },
						NeoTreeIndentMarker = { fg = c.base },
						SatelliteBar = { bg = c.surface0, blend = 15 },
						SpectreBorderCustom = { fg = c.surface0 },
						SymbolUsageText = { fg = c.surface2 },
						Visual = { bg = c_blend(c.base, c.surface2, 30) },
					}
				end,

				latte = function(c)
					return {
						AerialGuide = { fg = c.crust },
						GitSignsCurrentLineBlame = { fg = c.surface0 },
						IlluminatedWordRead = { bg = c_blend(c.base, c.surface2, 20) },
						IlluminatedWordText = { bg = c_blend(c.base, c.sapphire, 10) },
						IlluminatedWordWrite = { bg = c_blend(c.base, c.sapphire, 10) },
						NeoTreeIndentMarker = { fg = c.surface0 },
						SatelliteBar = { bg = c.crust, blend = 15 },
						SpectreBorderCustom = { fg = c.crust },
						SymbolUsageText = { fg = c.surface0 },
						Visual = { bg = c_blend(c.base, c.crust, 85) },
					}
				end,
			},
		},
	},
}
