#!/usr/bin/env lua

-- stylua: ignore
os.execute( "[ ! -d $HOME/.local/share/sketchybar_lua/ ] && (git clone https://github.com/FelixKratz/SbarLua.git /tmp/SbarLua && cd /tmp/SbarLua/ && make install && rm -rf /tmp/SbarLua/)")
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/?.so"

local sbar = require("sketchybar")

sbar.begin_config()
require("init")
sbar.hotload(false)
sbar.end_config()

sbar.event_loop()
